name: mpv
defaults:
  run:
    shell: bash

permissions:
  actions: write
  attestations: write
  contents: write

on: 
  workflow_dispatch:
    inputs:
      release:
        description: "Publish a release"
        required: false
        default: false
        type: boolean

jobs:
  build_qjs:
    name: Build qjs
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@main
        with:
          ref: qjs
      - name: Install dependencies
        run: |
          mkdir -p llvm build/install
          url=$(curl -sL \
                     -H "Accept: application/vnd.github+json" \
                     -H "X-GitHub-Api-Version: 2022-11-28" \
                     https://api.github.com/repos/mstorsjo/llvm-mingw/releases/tags/nightly \
                     | jq -r '.assets[] | select(.browser_download_url | match("ucrt-ubuntu.*x86_64")) | .browser_download_url')
          echo "Downloading & installing llvm-mingw"
          curl -sLO $url && echo "llvm-mingw is successfully downloaded "
          filename=$(basename $url .tar.xz)
          tar -xJf $filename.tar.xz -C $PWD/llvm --strip-components=1 $filename/bin $filename/lib --exclude "aarch64*" --exclude "arm64ec*" --exclude "armv7*" &&
          tar -xJf $filename.tar.xz -C $PWD/build/install --strip-components=1 $filename/generic-w64-mingw32 $filename/x86_64-w64-mingw32 &&
          echo "llvm-mingw is successfully installed"
      - name: Build
        id: build
        run: |
          mkdir -p release

          cmake -Wno-dev --fresh -DTARGET_ARCH=x86_64-w64-mingw32 -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/llvm -DMINGW_INSTALL_PREFIX=$PWD/build/install/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUST_LOCATION=$HOME -G Ninja -B $PWD/build -S $PWD

          ninja -C $PWD/build download || true
          ninja -C $PWD/build update
          ninja -C $PWD/build qjs-fullclean
          ninja -C $PWD/build qjs
      - name: Collect logs
        if: ${{ always() }}
        run: |
          sudo 7z a logs.7z $(find build -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log")
      - name: Upload logs
        uses: actions/upload-artifact@main
        if: ${{ always() }}
        with:
          name: logs
          path: logs.7z
      - name: Upload qjs
        uses: actions/upload-artifact@main
        with:
          name: qjs
          path: |
            build/qjs/qjs.exe
            build/qjs/libwinpthread-1.dll
      - name: Job summary
        uses: actions/github-script@main
        continue-on-error: true
        if: ${{ always() }}
        with:
          script: |
            const path = require('path');
            const { readdirSync,existsSync } = require('fs');
            const myExec = async (command, args = null) => await exec.getExecOutput(command,args,{silent: true}).then(result => result.stdout.trim()).catch(err => '');
            
            const rootdir = process.cwd();
            const workdir = path.resolve(rootdir,"src_packages");
            const isGitSync = dirname => existsSync(path.join(workdir, dirname, '.git'));
            
            const getGithubUrl = (hash,remote) => remote.replace(/\.git$/,"") + `/commit/${hash}`;
            function getCommitUrl(hash,remote) {
                let url = "";
                switch (true) {
                  case /github\.com/.test(remote):
                    url = getGithubUrl(hash,remote);
                    break;
                  default:
                    url = remote;
                    break;
                }
                return url;
            }
            async function repo_info(dir){
              let local_hash = await myExec(`git -C ${dir} rev-parse --short=7 HEAD`);
              let remote_branch = await myExec(`git -C ${dir} rev-parse --abbrev-ref HEAD@{upstream}`);
              let remote_hash = await myExec(`git -C ${dir} rev-parse ${remote_branch}`);
              let status = await myExec(`git -C ${dir} status -sb`).then(s => s.split("\n",1)[0].replace(/^## */,""));
              let remote = await myExec(`git -C ${dir} config --get remote.origin.url`);
              return [local_hash, remote_hash, status, remote]
            }
            
            async function generateGitInfoTable(targetDir){
              const dirs = readdirSync(targetDir, { withFileTypes: true })
                .filter(dirent => dirent.isDirectory() && isGitSync(dirent.name) )
                .map(dirent => path.join(targetDir, dirent.name));
              let info_table = [[{data: 'Package', header: true}, {data: 'Local commit', header: true}, {data: 'Status', header: true}, {data: 'Remote commit', header: true}]];
              for (let dir of dirs) {
                [local_hash, remote_hash, status, remote] = await repo_info(dir)
                let url = getCommitUrl(remote_hash, remote);
                let package_name = path.basename(dir);
                info_table.push([package_name, local_hash, status, `<a href="${url}">${remote_hash.slice(0,7)}</a>`]);
              }
              return info_table;
            }

            await core.summary.clear();
            let packages_table = await generateGitInfoTable(workdir);
            packages_table = core.summary.addTable(packages_table).stringify();
            await core.summary.clear();
            
            const exec_path = path.join(rootdir,'build','exec');
            const clang_version = (await myExec(`${exec_path}`,["clang","--version"])).split('\n')[0];

            core.summary
              .addRaw(`Compiler:`,true)
              .addRaw(`${clang_version}`,true);
            await core.summary.addDetails('Packages Version',packages_table).write();
